import { LandingNav, LandingFooter } from "@/components/landing";
import { createClient } from "@/lib/supabase/server";
import { BRAND } from "@/lib/brand";

export default async function TermsOfService() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  return (
    <div className="min-h-screen bg-surface-0 flex flex-col">
      <LandingNav user={user} />
      <main className="flex-1 container mx-auto px-4 py-16 md:py-24 max-w-4xl">
        <div className="prose dark:prose-invert prose-slate max-w-none">
          <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString()}</p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
            <p className="mb-4">
              By accessing and using {BRAND.name} (&quot;the Service&quot;), you agree to comply with and be bound by these Terms of Service. If you do not agree, strictly do not use the Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
            <p className="mb-4">
              {BRAND.name} is an AI-powered notebook and research assistant. It allows users to upload documents (PDF, text, etc.) and interact with them using generated chats, podcasts, and summaries.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">3. User Responsibilities</h2>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li>You must be at least 13 years old to use the Service.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must not upload illegal, harmful, or infringing content.</li>
              <li>You agree not to reverse engineer or attempt to disrupt the Service.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">4. AI Disclaimer</h2>
            <p className="mb-4">
              <strong>Accuracy:</strong> The outputs generated by our AI models (summaries, answers, podcasts) may contain errors or "hallucinations." You should verify important information independently. We do not guarantee the accuracy of AI-generated content.
            </p>
            <p className="mb-4">
               <strong>Ownership:</strong> As between you and {BRAND.name}, you retain ownership of your original uploaded content. You are granted rights to the generated outputs for your personal or commercial use, subject to these Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">5. Google Drive Integration</h2>
            <p className="mb-4">
              By using our Google Drive integration, you authorize us to access the specific files you select. This access is used solely to import content into your notebook for analysis.
            </p>
          </section>

         <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">6. Termination</h2>
            <p className="mb-4">
              We reserve the right to suspend or terminate your access to the Service at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users of the Service, us, or third parties, or for any other reason.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">7. Limitation of Liability</h2>
            <p className="mb-4">
              To the fullest extent permitted by law, {BRAND.name} shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits of data, arising out of your use of the Service.
            </p>
          </section>
        </div>
      </main>
      <LandingFooter />
    </div>
  );
}
