"""add_updated_at_to_document_and_content

Revision ID: 06998810b3f7
Revises: b2c7d4e5f6a1
Create Date: 2026-01-15 03:39:19.810731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06998810b3f7'
down_revision: Union[str, Sequence[str], None] = 'b2c7d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add updated_at columns to document and generatedcontent
    op.add_column('document', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('generatedcontent', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    
    # Remove server_default after initial population so future updates use onupdate
    op.alter_column('document', 'updated_at', server_default=None)
    op.alter_column('generatedcontent', 'updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generatedcontent', 'updated_at')
    op.drop_column('document', 'updated_at')
    # ### end Alembic commands ###
