"""Add task_progress table

Revision ID: 09c618e11b5a
Revises: 5bafb849dbfe
Create Date: 2026-01-14 21:34:23.213464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09c618e11b5a'
down_revision: Union[str, Sequence[str], None] = '5bafb849dbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('content_id', sa.Uuid(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_progress_content_id'), 'task_progress', ['content_id'], unique=False)
    op.create_index(op.f('ix_task_progress_document_id'), 'task_progress', ['document_id'], unique=False)
    op.create_index(op.f('ix_task_progress_job_id'), 'task_progress', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_progress_job_id'), table_name='task_progress')
    op.drop_index(op.f('ix_task_progress_document_id'), table_name='task_progress')
    op.drop_index(op.f('ix_task_progress_content_id'), table_name='task_progress')
    op.drop_table('task_progress')
    # ### end Alembic commands ###
