"""make_user_hashed_password_optional_for_oauth

Revision ID: 8e2ad4f1f629
Revises: 2f3e4d5c6a7b
Create Date: 2026-01-18 15:34:22.575668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e2ad4f1f629'
down_revision: Union[str, Sequence[str], None] = '2f3e4d5c6a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Make user.hashed_password nullable with default empty string for OAuth users
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True,
               server_default='')
    
    # Update existing NULL values to empty string (if any)
    op.execute("UPDATE \"user\" SET hashed_password = '' WHERE hashed_password IS NULL")
    
    # Skip procrastinate table drops - they're managed separately by procrastinate
    # op.drop_index(op.f('idx_procrastinate_workers_last_heartbeat'), table_name='procrastinate_workers')
    # op.drop_table('procrastinate_workers')
    # ... etc
    
    # Only apply task_progress FK changes
    try:
        op.drop_constraint(op.f('fk_task_progress_document_id'), 'task_progress', type_='foreignkey')
    except Exception:
        pass  # Constraint might not exist
    try:
        op.drop_constraint(op.f('fk_task_progress_user_id'), 'task_progress', type_='foreignkey')
    except Exception:
        pass
    try:
        op.drop_constraint(op.f('fk_task_progress_content_id'), 'task_progress', type_='foreignkey')
    except Exception:
        pass
    try:
        op.drop_constraint(op.f('fk_task_progress_notebook_id'), 'task_progress', type_='foreignkey')
    except Exception:
        pass
    
    op.create_foreign_key(None, 'task_progress', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'task_progress', 'document', ['document_id'], ['id'])
    op.create_foreign_key(None, 'task_progress', 'notebook', ['notebook_id'], ['id'])
    op.create_foreign_key(None, 'task_progress', 'generatedcontent', ['content_id'], ['id'])
    # ### end Alembic commands ###




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert user.hashed_password changes
    # First set any empty passwords to a placeholder (needed before making NOT NULL)
    op.execute("UPDATE \"user\" SET hashed_password = 'OAUTH_USER_NO_PASSWORD' WHERE hashed_password = ''")
    
    # Make hashed_password non-nullable again
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default=None)
    
    op.drop_constraint(None, 'task_progress', type_='foreignkey')
    op.drop_constraint(None, 'task_progress', type_='foreignkey')
    op.drop_constraint(None, 'task_progress', type_='foreignkey')
    op.drop_constraint(None, 'task_progress', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_progress_notebook_id'), 'task_progress', 'notebook', ['notebook_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_task_progress_content_id'), 'task_progress', 'generatedcontent', ['content_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_task_progress_user_id'), 'task_progress', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_task_progress_document_id'), 'task_progress', 'document', ['document_id'], ['id'], ondelete='SET NULL')
    
    # Skip procrastinate table recreation - they're managed separately
    # ### end Alembic commands ###

