"""feedback table

Revision ID: be7e73646e07
Revises: 8e2ad4f1f629
Create Date: 2026-01-25 02:36:52.635881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be7e73646e07'
down_revision: Union[str, Sequence[str], None] = '8e2ad4f1f629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.Enum('chat_response', 'podcast', 'quiz', 'flashcard', 'mindmap', name='feedbackcontenttype'), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Enum('thumbs_up', 'thumbs_down', name='feedbackrating'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_content_id'), 'feedback', ['content_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)

    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))

    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_content_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
